# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c32a0dce0c392da5577c7aa05cc5aa859ccb0761d00825271b17cfa36d7d93c529b1f703316d2047e863f3e17ec4866f686084970eaecc35b05fa58bd4b47c43

test:
  secret_key_base: b5fa0838440f3220976560e2820b586bef2a67c3cf2848162f2fa672fba2e4603f577ce753533a77ebb490d98f65495d209ab0b22e192fd1dd62296ba34c406c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
